### ISSUE TITLE
Result aggregator has quadratic time complexity

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/bigtest#1017]
As the number of nodes in the test tree increases, the number of checks we perform in the result aggregator increases quadratically. With a big test suite, such as the material-ui interactors suite, we end up performing a gigantic number of checks.

I figured this out by creating a flamegraph while running the material ui interactors suite and observing that a huge amount of time was being spent in the result aggregator. The solution is to rewrite the result aggregator with a better algorithm.

**Comment by cowboyd** [comment]
😱 😱 😱

**Comment by jnicklas** [comment]
This is now fixed
