### ISSUE TITLE
Old website deprecation

### ISSUE THREAD

**Issue by jorgelainfiesta** [thefrontside/bigtest#114]
## Motivation 

We're creating a new website, given that the old website and what it documents has been almost completely abandoned. However, there are already URLs indexed and people may have bookmarked and content available that may still be relevant for the users of the current release.

## Solution

1. Add a deprecation note to every page of the old website. The notes should outline the current status of the project in relationship to that page and link to the new website.
<img width="1341" alt="Screenshot 2020-02-07 at 17 12 51" src="https://user-images.githubusercontent.com/4451393/74045480-22408b00-49cd-11ea-90e3-6ae587abf8d2.png">

2. Deploy the old site to `v1.bigtest.io`
3. Update the old site repo's README with a note about the situation.
4. Close all outstanding issues and PRs on the old repo explaining the situation.

5. Set up redirects on the new website to handle all `/guides/**` and `/docs/**`, land them on a page that contains a note explaining the situation of the library. We can redirect them all to `/?from-old-website=true` for example, and then show a note on the current landing page. 
This note must contain a link that takes the user to what it was looking for on `v1.bigtest.io`.

<img width="1552" alt="Screenshot 2020-02-07 at 17 25 08" src="https://user-images.githubusercontent.com/4451393/74046422-d68ee100-49ce-11ea-9bd3-aa1f9008d3df.png">

These redirects will be temporary. They will be in place until we have the new `/guides` and `/docs` ready.

**Comment by minkimcello** [comment]
> 1. Add a deprecation note to every page of the old website. The notes should outline the current status of the project in relationship to that page and link to the new website.

Does that mean when they're at `oldbigtest.io/docs/convergence` on the old website, the link of the warning should lead them to the new `newbigtest.io/docs/convergence`? What happens if the new docs doesn't have a corresponding page from the old docs?

> 5. Set up redirects on the new website to handle all `/guides/**` and `/docs/**`, land them on a page that contains a note explaining the situation of the library. We can redirect them all to `/?from-old-website=true` for example, and then show a note on the current landing page. 
This note must contain a link that takes the user to what it was looking for on `v1.bigtest.io`.

I don't know how the bigtest api is being rewritten for the new release but could it be that users need to review all the changes instead of just one of the packages? So in that case, wouldn't it make more sense for all the warnings (from question no. 1) to link to the main page of docs (or even the homepage) with the `/?from-old-site=true`?

Because I'm thinking if they're looking at `package A` from the old site and they get redirected to `package A` of the new site, the explanation might inevitably lead to `these are the differences for package A [ . . . ] but you must also look at package B to understand`.

**Comment by jorgelainfiesta** [comment]
`Does that mean when they're at oldbigtest.io/docs/convergence on the old website, the link of the warning should lead them to the new newbigtest.io/docs/convergence? What happens if the new docs doesn't have a corresponding page from the old docs?`

No, sorry it wasn't clear. The new guides do not exist and will not in a while so we should just point them to the landing page of the new site.

`I don't know how the bigtest api is being rewritten for the new release but could it be that users need to review all the changes instead of just one of the packages? [...]`

All the links from the old site (`v1.bigtest.io/**/**`) should just link to the new site landing page on the warning page.

Now, what `5` refers to is a flow as follows (and it's only temporary for the transition period):

i. The user tries to access `bigtest.io/guides/**`, because she's looking for the old site. 
ii. Instead of displaying a 404 (because that page does not exist in the new site), we redirect to the current page index page, but add a query parameter to show the `from-old-site` message and another `original-path` query param, to build the link in the archive site for what she was looking for.
iii. We show the index page with the message about the new version, offering to visit the archived page she was looking for before.

This mechanism will be removed when we have the new guides.

**Comment by jorgelainfiesta** [comment]
Given redirects limitations on Netlify, we'll change the approach of `5`.

Instead of issuing redirects to the landing page, we'll have a `/guides` route on the new website that catches all `/guides/**` and displays a message explaining the new website and how they can access the archived website.

**Comment by jorgelainfiesta** [comment]
Now that #128 is merged, this issue is completed.
