### ISSUE TITLE
How to handle harness injection on subsequent iframes

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#137]
Right now, we inject the harness script into the head of any request that is coming to the application with context type text/html.

However, let's say that an application under test was using an `iframe` to do something like load a navigation bar? What should we do in that case?

**Comment by jnicklas** [comment]
I thought about this a bit, and I think it's probably fine to inject the harness unnecessarily in some cases. The harness shouldn't really do anything unless we tell it to, so just having it be there shouldn't be a problem.

Also, in the iframe case, we probably actually *do* want the harness to be injected. Imagine if the page in the iframe makes an AJAX request, we probably want that to hit out faked out API.

**Comment by cowboyd** [comment]
We can probably have the harness when it connects to the agent report its own url, which we can use to determine the "role" of the frame which would allow us to differentiate between different harnesses.

**Comment by cowboyd** [comment]
I'm closing this since we're not going to be covering this case in MVP
