### ISSUE TITLE
How to "arrange" the browser environment from the test-case

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#138]
In some cases, we want to begin the browser in a particular state before booting the application and navigating to a url. The most common case of this is setting up local storage with authentication information so that the app begins its run. However, some tests you'll want to actually test login/logout and you _won't_ want have local storage setup in a given way.

The problem is how to specify this on a per-test basis. The reason this requires special attention is that some actions would need to run _before_ the app boots, whereas other run _after_. 

The harness itself is loaded _before_ the app, so how do we mark certain steps as running immediately, before anything else? Also, these steps cannot be asynchronous, because the app _will_ continue loading once the `harness.js` script is finished executing.

Another option is to do some two-phased loading where we prepare the iframe first, and then proceed to load the app, but I'm not sure exactly how this will work.

**Comment by jnicklas** [comment]
Uff, this is a tough issue. I have some ideas for workarounds, but this is a potential showstopper we really haven't paid enough attention to. 🤯

**Comment by cowboyd** [comment]
This has been fixed by making the agent and the harness running on the same domain #377
