### ISSUE TITLE
What are the responsibilities of the Agent?

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#141]
Right now, our agent successfully logs "Hello World" into the host application. Given the steps required to get there, this is actually more awesome than it seems.  Ultimately though, it will need to become more complex than that. 

This quest is to document how the agent will carry out its work of controlling the application under test, and communicating with / responding to requests from the server.

Key questions: 

* What are use-cases to cover, and what would complete sequence diagrams of those use-cases look like.
* What are some hypothetical examples?
* What *server* features will be necessary in order to support the agent.
* What are the major exception conditions that we foresee?

**Comment by jnicklas** [comment]
I think we can close this issue for now.
