### ISSUE TITLE
Optionally allow orchestrator to serve agent pre-compiled assets

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#150]
The `agent` is the master application running Innside of connected browsers that uses the `harness` (which runs inside of an iframe) to run tests against and application. Currently, we are using parcel to build and serve the agent to the browser. This is convenient for development when agent code is under heavy development. However, in production, the agent is never going to change and so we don't want to pay the startup time and resources to fire up a parcel server. Instead, let's add the ability to serve the agent not from parcel, but from a simple static file server.

**Comment by cowboyd** [comment]
I think the flow here is to support first building and packaging the orchestrator. Then, having the start script compile the orchestrator first, and then run it. This will be a natural consequence of preparing it for distribution

**Comment by jnicklas** [comment]
This is fixed :)
