### ISSUE TITLE
Define confile file location and format

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/bigtest#155]
In addition to thefrontside/bigtest#153, we'll also want to define some kind of configuration file and rules about where it can be located. There is some overlap with thefrontside/bigtest#153 here in that maybe there is some relation between the data directory and the config file.

We need a config file, because there are certain properties which will be specific to the application under test, the most obvious is the command needed to start the application, but also things like test file location should be configurable.

While we could provide these arguments every time we run a CLI command, that is just very inconvenient.

**Comment by cowboyd** [comment]
Yeah, I'm not a big fan of plopping it in package.json either.

I'd say put it in `.bigtest/bigtest.json`, or go full baller and put it in the project home with a `.bigtest.json`, `.bigtest.toml` or whatever format we end up going with.

**Comment by cowboyd** [comment]
We have a `.bigtest.json` specified by `@bigtest/project`
