### ISSUE TITLE
Add DSL which compiles to test suite format

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/bigtest#157]
We have defined the JSON structure which is expected for a test suite, but writing this JSON structure by hand is quite cumbersome. We should have a nice DSL for defining this structure. Ideally it would be typescript aware, so we can provide good typings for typescript.

**Comment by cowboyd** [comment]
A vanilla DSL was been implemented with #273 It should be noted, however, that any DSL is possible, so long as it emits a `TestImplementation`.
