### ISSUE TITLE
What is the best way to connect the App?

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#158]
for the MVP and forward, we want to be able to support specifying the app on the command line:

```
$ bigtest --app http://localhost:24000 --start 'yarn start'
```

Or store it in a `.bigtest.json` file:

```
{
  "app": "http://localhost:24000",
  "start": "yarn start"
}
```

or point it to a running site:

```
$ bigtest --app http://production.mydomain.io
```

These should work on subsequent invocations of the CLI against a single running server, but right now this is problematic because the app is specified at system startup, so if we want to change the configuration file, or run with different CLI parameters right now, we'd have to restart the server from the CLI.... something we'd like to avoid.

What if the `app` was configured dynamically and was exposed via our graphql interface?

```graphql
type App {
  name: String!
  url: String!
  status: 'unreachable' | 'error' | 'online'
}

type Mutation {
   setApp($name: String! = "default", url: String!);
}
```

By default, we'd start with the empty app, which would just load an empty `<html></html>`, and then the CLI could set the app before running the test suite.

This has the flexibility of not coupling the lifecycle of the app to the lifecycle of the bigtest server.

**Comment by jnicklas** [comment]
We settled on doing this via the configuration file for now.
