### ISSUE TITLE
It's a tough look to deprecate when you're not actually replacing with anything.

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#177]
See comment here 

https://github.com/thefrontside/bigtest/pull/175#pullrequestreview-365244694

Until we actually have a replacement, we need the deprecation warning to not be a warning, but a informational helper that new things are underway.

**Comment by jorgelainfiesta** [comment]
https://github.com/bigtestjs/bigtestjs.io is archived so I couldn't submit a PR to change the copy. However, I pushed an update to Heroku.

The title now reads:
```
Heads up, we are working on a new BigTest
``
