### ISSUE TITLE
Preview builds should use push event

### ISSUE THREAD

**Issue by taras** [thefrontside/bigtest#229]
pull_request event runs GitHub actions on many events. This can create a situation where same commit causes GitHub Actions to run multiple times. Preview actions fails when its ran multiple times on the same commit because a preview for the commit is published by another instance of that job. We should switch to push event or use a more specific pull_request event for running our actions. 

### Example failure

![image](https://user-images.githubusercontent.com/74687/79338334-1acdbe80-7ef5-11ea-91d7-06297bc97d32.png)

PR: https://github.com/thefrontside/bigtest/pull/225#issuecomment-611190253
Run: https://github.com/thefrontside/bigtest/pull/225/checks?check_run_id=582437910

More info here https://github.com/resideo/zeus/pull/509

**Comment by minkimcello** [comment]
Hmm I'm not sure how to replicate the issue but we can use `!` syntax on `push` to avoid running the preview action on `master` on `push`.

Now the issue would be to prevent it from running unless it's a pull request which I could put as a conditional at the beginning of the workflow. But that means the workflow will start up for each push which **shouldn't** be an issue I think (except to prevent the rest of the workflow from running I think we need to trigger an error).

Also I usually create my pull request on my first push anyway but if that's not the case for others, we might end up having the actions tab becoming cluttered.

So..

A. Keep it as is and accept the occasional error as inevitable cost.
B. Change it to `on push` but...
  - Prevent on master
  - Run only on pull requests
    - Workflow will run on each push and return an error/fail unless it's a PR

I tried to see if nesting webhooks was a thing but couldn't find any resources and I don't know how to trigger the double-run-on-same-commit to test it.

**Comment by cowboyd** [comment]
What if we built and uploaded the packages on push, so that there was a list of packages associated with every single commit, and then the pull request just made sure that the latest from all the packages associated with the range of commits of the PR were published and tagged?

**Comment by cowboyd** [comment]
@taras @minkimcello Is this still relevant given that this will be superceded by the release manager? If not, let's close it out.

**Comment by minkimcello** [comment]
👌
