### ISSUE TITLE
Loading of context.ts fails in compiled package

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/bigtest#244]
Since #243, we are pulling in the file `src/schema/context.ts` by specifically loading it here:

https://github.com/thefrontside/bigtest/blob/f653e7ac901df894f9f2cb5200225cc68e2f9299/packages/server/src/schema.ts#L15

However, this does not work when running the server as a compiled package, since the file now has the extension `.js` instead of `.ts`.

This generates a warning like this:

```
GraphQL Nexus: Unable to find file or module /Users/jonasnicklas/Projects/bigtest/packages/server/dist/src/schema/context.ts, skipping
```

**Comment by cowboyd** [comment]
_shakes fist at the skies_

**Comment by jnicklas** [comment]
Hmm, seems like this is now causing hard failures for me :(

```
GraphQL Nexus: Unable to find file or module /Users/jonasnicklas/Projects/bigtest/packages/server/dist/src/schema/context.ts, skipping


Missing required typegen import: ctx
```
