### ISSUE TITLE
Update Social Media Logo for BigTest

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#247]
When we drop a link to the bigtest repo in chat, previews as the Frontside logo. However, we've got a nice logo for bigtest... we should use it. Let's update the social preview setting at  https://github.com/thefrontside/bigtest/settings to use it.

**Comment by minkimcello** [comment]
![Screen Shot 2020-04-21 at 12 54 26 PM](https://user-images.githubusercontent.com/29791650/79891698-5e319c80-83cf-11ea-926c-d487d1f37f21.png)
![Screen Shot 2020-04-21 at 12 55 04 PM](https://user-images.githubusercontent.com/29791650/79891700-5e319c80-83cf-11ea-9d95-2fe3f3e2f06c.png)

**Comment by cowboyd** [comment]
beeeyootiful 😍
