### ISSUE TITLE
Better error messaging if manifest fails to load.

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#279]
If the manifest bundle containing all of the test definitions is bad in any way, this crashes the server when it tries to load the manifest.

1. How do we report the fact that the manifest is bad to the server dashboard?
2. How do we report the fact that the manifest was bad when running a test?
3. How do we report it in our CI runner?

**Comment by cowboyd** [comment]
I think we want to maintain the bundle in the `OrchestratorState`, this will let us make better UI on top of what the bundle is currently doing, e.g. we could have the bundle be something like "unknown" | "building" | "errored" | "green". That way, if you request a test run and it is not "green" we can issue a warning: "Tests are currently not building... running tests against last built version"

**Comment by cowboyd** [comment]
The following test suite can reproduce this error:

```ts
export default test('Basic Test').child()
```

Note that this is invalid typescript, so it actually should never even try to load it. See #280 #443

**Comment by dagda1** [comment]
a `RollupError` looks like this

```javascript
{
  pos: 32,
  loc: {
    file: '/Users/developer15/projects/bigtest/packages/server/test/fixtures/error.t.js',
    line: 2,
    column: 15
  },
  raisedAt: 43,
  frame: '1: export default {\n2:   description: "Signing In\n                  ^\n3: }',
  id: '/Users/developer15/projects/bigtest/packages/server/test/fixtures/error.t.js',
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  plugin: 'commonjs',
  watchFiles: [
    '/Users/developer15/projects/bigtest/packages/server/tmp/test/orchestrator/manifest/src/manifest.js',
    '\u0000rollup-plugin-inject-process-env',
    '/Users/developer15/projects/bigtest/packages/server/test/fixtures/empty.t.js',
    '/Users/developer15/projects/bigtest/packages/server/test/fixtures/raw-tree-format.t.js',
    '\u0000/Users/developer15/projects/bigtest/packages/server/test/fixtures/raw-tree-format.t.js?commonjs-proxy',
    '\u0000/Users/developer15/projects/bigtest/packages/server/test/fixtures/empty.t.js?commonjs-proxy',
    '\u0000/Users/developer15/projects/bigtest/packages/server/test/fixtures/error.t.js?commonjs-proxy',
    '/Users/developer15/projects/bigtest/packages/server/test/fixtures/error.t.js'
  ]
}
```
And of course, you have a stack trace.

For this issue, I am just going to add that to the state.

Displaying that in a meaningful fashion is for a different PR.

**Comment by dagda1** [comment]
tslog does some cool stuff to get really good error messages

<img width="1134" alt="logger" src="https://user-images.githubusercontent.com/118328/93389230-c17f0800-f863-11ea-9f74-280b848f47e5.png">

I would have liked to use `tslog`, the error logger is better than the one we currently have or alternatively [here is the cool bit with codeframes](https://github.com/fullstack-build/tslog/blob/master/src/LoggerHelper.ts#L219).
