### ISSUE TITLE
CI-ready command for the CLI

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#283]
We have two commands `bigtest server` and `bigtest test` The second connecting to the server created by the first to run the tests.

While this setup is doable for long-running test sessions like happen during development (it can be enhanced but for now it's ok), we have to have a single command that "just works" inside CI environments.

either as an option via `bigtest test --ci` or using an entirely separate command `bigtest ci` the command should

1. stream progress of steps via dots
2. print a really nice summary of what went wrong (if anything)

**Comment by jnicklas** [comment]
This is done. The implementation needs some TLC, but it does work, so I'm closing this for now.
