### ISSUE TITLE
Proposal: agent/harness responsibility and communication tweaks for wider applicability

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/bigtest#286]
While lying in bed last night, I was thinking about interactors and how they would work, and my mind got stuck on a question: what happens if you navigate away from the page in the middle of an interaction? I realized that this question is actually broader than just interactors: what happens if you navigate away in the middle of a test?

So far, we have assumed that bigtest would be used to test SPAs, but what if that didn't have to be true? Can we actually use bigtest to test classical request/response applications? After thinking about this for a while, I think with some minor architecture tweaks we actually can! And just as an added bonus, I think this design also solves the most serious architecture problem that we've punted on so far.

### Status quo

Let's review on how the agent and harness interact at the moment and their respective responsibilities:

The agent will receive a message from the orchestrator telling it to run some tests, the orchestrator attaches a listing of all tests it wants to run to this message. The agent takes this data structure and splits it into *lanes*, since our tests are structured as trees, there is one lane for each leaf node in the tree. The agent then tells the harness that it want to run a particular lane, it does this by giving the harness the path of the leaf node that the lane ends in. The harness then loads the application, loads the test manifest, finds the lane in the manifest and runs the lane and reports the results of doing so to the agent, which in turn sends them to the orchestrator.

### Problems with the current approach

1) We have previously realized that the Harness cannot maintain state across tests, since as soon as it reloads the page, all state will be lost. We solved this by moving the state of the test run to the agent. However, there is still a huge amount of state on the Harness today: the current state of each test lane. Also, a vexing problem here is that we cannot in any way persist this state, since the state is code, not data (we ain't writing this in LISP 😉), so part of our state is where we are right now in a procedure, and this is something we cannot serialize or deserialize in any way. This works fine for SPAs, but it won't work if the application does any page reloads in between. Imagine a test like this:

``` javascript
step("go to product page", async () => {
  await Link("Products").click(); // navigates to product page
  await Link("Hoverboard").click();
});
```

If we navigate away in the middle of this step, how could we possibly "resume" by jumping back into the middle of this step?

2) A second problem we have come up with is that we might want to preload some state. For example, imagine setting some authentication data by setting it in local storage. A problem then is, when do we load the application? To have the harness available, we need to load the app, but if the app is already loaded, it is too late to set the state. We'd ideally like to set the state up as part of the test itself, but this is tricky to do with the current design. We realized that this would be a problem a while ago, but punted on this, since we thought that we could come up with a solution as the problem manifests itself.

3) Finally a minor problem with the current design is the communication between the agent and harness, which is sort of inelegant. The lane splitting in the agent needs to be communicated to the harness in an awkward sort of way, and yet we don't even do everything we want here yet. Eventually we'd like to skip running assertions if a test is run multiple times, which it could be if it is part of multiple lanes. With the current design this is awkward, which is why we don't do it yet. With the proposed new design it will be very easy to implement.

### The Solution

With all of this exposition, the solution should already be pretty obvious:

We move the running of the lanes to the agent instead.

This means that the harness loses all responsibility for actually running the tests, the agent is completely responsible for this. This means that we don't need to coordinate between the agent and the harness anymore.

A problem then presents itself: if we run the tests in the agent, how do we actually interact with the application page? At first I had some crazy ideas about having the interactors send messages to the iframe, but then I realized that there is a much simpler solution: simply interact with the [`contentDocument`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/contentDocument) directly.

A complication presents itself in that the `contentDocument` is only accessible if the iframe is on the [same origin](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) as the parent frame, that is it has the same protocol, domain and **port** as the parent. However, since we are already running a proxy server for the application, this is actually solvable! All we need to do is run the agent on the same port as the proxy server, but have it serve up the agent under a hidden URL. Something like `http://localhost:26002/__agent__` or something else which is unlikely to conflict with the main application.

If we adopt this solution, we can actually defer the loading of the application, until the test author explicitly decides to load it (or maybe the first time they use an interactor?) this way we can set up state before the app ever even loads, neatly solving the second problem as a happy biproduct.

And since all state is maintained on the agent, it will be easy to see whether a particular test has already run as part of another lane and skip its assertions.

### Conclusion

This change will require some change to the bigtest architecture, they don't really change anything fundamental, but it will take a bit of work to make this all work together. However, I think the fact that this gives us the ability of running bigtest against non-SPAs is such a huge deal that we should do this regardless.

**Comment by jnicklas** [comment]
cc @taras @cowboyd

**Comment by taras** [comment]
@jnicklas the line between agent and harness is blurry to me, but the fact that this realization comes from considering mobile use case suggests to me that we're moving in right direction. I have one question.

If we make this change, what will be the new responsibility of the harness in web testing?

**Comment by cowboyd** [comment]
🤯 🤯 🤯  This sounds very promising @jnicklas ! In addition to what you have listed here, It's making me wonder all of the ways this new conception would simplify things. Off the top of my head.

1. We should be able to do away with the proxy script injection altogether right? Since we have access to the internals of the iframe before we load the application, there's no longer the requirement that the harness be the _very first thing to run_. The agent can just inject the harness script directly. In fact, we might be able to completely do away with the _harness entirely_ since we can read any state we need to off of the `contentDocument`, inject any scripts needed, evaluate any code needed.
2. Because the `contentWindow` of the `iframe` element will persist between documents, we can easily do handy stuff like overriding JavaScript common methods like  `console.log` or even nasty gotchas like `alert()` and `confirm()`

What assumptions do we need to validate with this?

**Comment by jnicklas** [comment]
@cowboyd 

1) I'm not sure, but I have a feeling we still need to do the script injection. It is really the only way we can ensure that our mocking infrastructure is set up synchronously. Actually, interestingly, we can use `localStorage` as a means of communication for this. The agent will put all state it wants to set up in localStorage, which the harness can synchronously read and set up on load. Pretty nifty and race condition free!

If we rely on using the `load` event to determine when the document has loaded, then we risk being too late.

2) I'm not sure how this works, does the iframe get its own global JS scope? I'm guessing yes, right?

**Comment by cowboyd** [comment]
@jnicklas Yes, I believe that `Window` object is the JavaScript browsing context, and it looks like it is persistent across multiple document loads within an iframe (if I undersstand correctly) https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/contentWindow

It looks service workers are viable for all requests on the same origin, so if our iframe is on the same origin as the agent, then the agent's service workers should be able to intercept all requests in the child frame. That would allow us to inject any scripts, or perform any network stubbing that we need... all on the client. We may still want to have a proxy in the orchestrator, but we might actually be able to move that over to the client.

**Comment by cowboyd** [comment]
Marking this as closed since we're now enjoying all these benefits 😎
