### ISSUE TITLE
Verify assumptions in test suite

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/bigtest#294]
There are two invariants in our test suite format that we should verify are met, and if they are not, the test suite should not be accepted:

1. All paths of descriptions should be unique. That is two steps/assertions cannot have the same description within the same test and two sibling tests cannot have the same description.

2. There should be a maximum depth that we allow for tests. This is mainly so we can express recursive queries in our graphql without running into problems.

**Comment by cowboyd** [comment]
@dagda1 @pittst3r Given recent upgrades in the bundler architecture, any idea how we can validate this?

**Comment by dagda1** [comment]
could these be linting rules?  

Should we have an `eslint-plugin-bigtest`?

something like [this](https://eslint.org/docs/rules/max-depth)

**Comment by cowboyd** [comment]
Yes, that is actually a great idea, and more evidence for establishing the bigtest tests as a separate bundle in order to make #443
