### ISSUE TITLE
How do we express filter conditions on interactors?

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/bigtest#310]
Some interactors will probably want to have pre-conditions or filters, which we want to use to narrow the scope of what to find. For example, an input field might be disabled. Interacting with a disabled field is not what we want, probably. So we'll want to exclude disabled fields from our search. But do we always want to exclude these fields? What if we DO want to use a disabled field, can we work with both from within the same interactor? Also, it would be pretty nice if we could get error messages like "tried to fill in field 'Email' but it was disabled" or something like this.

Capybara has [such a feature](https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selector/definition/button.rb#L35-L36), but it is a bit cumbersome, and the error messages generated aren't great. If we want to have this type of feature, we should take care to design it in such a way that it is intuitive and also generates great errors.

**Comment by cowboyd** [comment]
Maybe some sort of "constraint" API?

```ts
Button("Submit")
  .validate(assert, element => {
    assert(element.enabled, "must be enabled in order to click, but it was disabled"{
  })
  .click();
```

In practice though, it seems like most of the time you would want to add these constraints to the action itself, so that it would be defined within the `click()` action.

Also, it would be great to somehow have access to these contraints before test-run time. I'm not sure how that would work.

**Comment by jnicklas** [comment]
Hmm, interesting to add these constraints on the action, are there any cases where a filter should be allowed on one action, but not on another? I can't really think of any of the top of my head, but there might be cases?

I also, just started heading down a rabbit hole with regards to visibility. Capybara by default only matches "visible" elements. This is actually hugely helpful, since JS-heavy apps often do stuff like hiding content via CSS and this might prevent an element from being shown on the page, which means that a user wouldn't be able to interact with it, so we don't allow it either, though it is overrideable in the rare case where you DO want to interact with a hidden element.

The question then is what does "visible" even mean? Selenium has a `isDisplayed` method which tries to determine visibility of the element, and this is probably a good starting point, since it's been proven to be reasonably robust. With some digging I found their [implementation here](https://github.com/SeleniumHQ/selenium/blob/e09e28f016c9f53196cf68d6f71991c5af4a35d4/javascript/atoms/dom.js#L437-L518).  Selenium is Apache2 licensed, so I think with proper attribution we would be allowed to re-use this. This method is obviously pretty complicated, but I think that given that it's just a bunch of if-statements, it should be pretty fast, so I'm not too worried about it.

I also found [this npm package](https://www.npmjs.com/package/is-element-visible) for dermining element visibility, the [implementation is here](https://github.com/LuizAsFight/is-element-visible/blob/master/src/index.js). The implementation is a lot simpler, but also maybe less robust? Still this might be good enough for the time being.

**Comment by cowboyd** [comment]
That actually _would_ be hugely helpful, not only for the sake of correctness, but if we can surface all of these checks that we're doing. Enabled, visible, focused, then it becomes really easy to diagnose _why_ something failed. It would be great to say "tried to click on this thing, but it's opacity is 0", or "tried to type in input field X, but it is off-screen, and does not have focus"

**Comment by cowboyd** [comment]
> Hmm, interesting to add these constraints on the action, are there any cases where a filter should be allowed on one action, but not on another? I can't really think of any of the top of my head, but there might be cases?

One that pops to mind is focus. It is possible to focus on a disabled button, but not activate it. This makes sense if you're using a screen reader for example, and you need to navigate through possible actions, navigating to a button and finding it disabled is crucial information.
