### ISSUE TITLE
Better errors when app command fails

### ISSUE THREAD

**Issue by pittst3r** [thefrontside/bigtest#321]
This is what it looks like currently:

```
$ yarn test
yarn run v1.22.4
$ bigtest server
[orchestrator] starting
Error: 'yarn start' exited with non-zero exit code
    ... useless stack trace ...
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

We should surface the underlying error. In my case the error was this, which was an easy fix:

```
$ yarn start
yarn run v1.22.4
$ ts-node src/index.ts
Error: Cannot find module '/Users/rpitts/.../index.ts'
    ... useless stack trace ...
```

**Comment by jnicklas** [comment]
YES! This is extremely frustrating and we have to fix it!!!

**Comment by cowboyd** [comment]
Sketch of design:

appService has:

```ts
{
  stdout: { tail: string[], lastChunk: string };
  stderr: { tail: string[], lastChunk: string; };
}
```

`tail` is around 100 lines maybe? Or a hundred chunks? It's some buffer of some size.

**Comment by jnicklas** [comment]
How did we feel about this, is the current solution good enough for the beta? Should we close this? Or remove it from the milestone?

**Comment by cowboyd** [comment]
Yeah, I think it probably is good enough to add it for now. Output is ugly, but it does get printed to the console.

**Comment by dagda1** [comment]
What is the current solution?

Could we not do something nicer.

Like in my spike?  [error](https://github.com/thefrontside/bigtest/blob/reporter/packages/reporter/src/out/console/console.ts#L110).

Not this exact code but something like it.

We could use the `ErrorDetail` type an `ErrorStack` types before it gets here.

I think we could do a quick facelift and add some colour and then think about the proper cli.

**Comment by cowboyd** [comment]
Right now, we just include the output in the stack trace.

**Comment by cowboyd** [comment]
@dagda1 Actually, I lied. We don't print anything 😊 

Can we take a lightest touch approach and just add a simple output to the `Logger` whenever the app transitions into the crashed state?

**Comment by dagda1** [comment]
@cowboyd  how are you triggering the error?

**Comment by cowboyd** [comment]
Right here https://github.com/thefrontside/bigtest/blob/graceful-agent-shutdown/packages/server/src/app-server.ts#L36

Basically we have most of  the information we need there in the exit status we just don't ever display a) the fact that the app crashed or b) any of the details around the app when it did. In fact, it would be nice to log that the app is started.

<blockquote><img src="https://repository-images.githubusercontent.com/100052766/a3090380-83ce-11ea-9e4b-1d0396ecd24b" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/thefrontside/bigtest">thefrontside/bigtest</a></strong></div><div>Tests that speed up development, not slow it down. Contribute to thefrontside/bigtest development by creating an account on GitHub.</div></blockquote>
