### ISSUE TITLE
Atom package needs tests

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/bigtest#331]
Just caught a regression in the atom package introduced in the recent refactorings which wasn't caught, but probably would have been if we had unit tests for this package.

**Comment by cowboyd** [comment]
@jnicklas just looked at the test suite 😬 

What was the regression?

**Comment by jnicklas** [comment]
This was partially resolved by #342, though we still might want some more tests for `Slice`.

**Comment by cowboyd** [comment]
completed with #393
