### ISSUE TITLE
'@bigtest/interactor' not found in bundled suite

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#356]
When attempting to use '@bigtest/interactor' inside the release manager test suite, the harness is throwing a

`Error: Cannot find module '@bigtest/interactor'`

This causes actually causes the test suite to hang.

**Comment by jnicklas** [comment]
This might be a dumb question but... did you add it as a dependency? 😬

**Comment by cowboyd** [comment]
Yes, but it is a `devDependency`, I just tried it as a normal `dependency` and it worked which is odd, but might help us figure it out.

**Comment by cowboyd** [comment]
This has been resolved with the move to rollup.
