### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#40]

**Comment by Robdel12** [comment]
Can we add docs site to this same idea? Something that looks nice

**Comment by cowboyd** [comment]
Lol. Yes indeed. That's actually already on the list https://github.com/thefrontside/bigtest/projects/1 but we decided to stop converting project notes to issues.

**Comment by Robdel12** [comment]
Looks like we have a logo so we can close this issue out (#63 added the logo to the readme)
