### ISSUE TITLE
If a step returns an object, the runner barfs

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#423]
I had the following step in my test suite:

```ts
  .step("start GraphQL simulator", () => ({
    simulator: startBrowserSimulation()
  }))
```

where `startBrowserSimulation()` returns a `Promise<Simulator>`. This was actually a bug in my code, where I should have more properly written:

```ts
  .step("start GraphQL simulator", async () => ({
    simulator: await startBrowserSimulation()
  }))
```

But as such it caused the following error in the runner:

```ts
lane.ts:38 [agent] step failed Object Error: cannot find controller for [object Object]
    at t.n.createController (context.js:217)
    at t.n.enter (context.js:96)
    at n.fork (context.js:79)
    at n.e.advance (control.js:84)
    at n.e.trapExit (control.js:102)
    at t.n.finalize (context.js:168)
    at t.n.resume (context.js:131)
    at t.call (control.js:133)
    at t.n.enter (context.js:101)
    at n.fork (context.js:79)
```

We should fix this bug, but my question is: how do we prevent this foot shot? of making sure that when you inject the resolution of a promise into a context, that you put the resolved value, not the promise... In other words, make sure you return a value that will result in:

```ts
{
  simulation: Simulation
}
```

not

```ts
{
  simulation: Promise<Simulation>
}
```

**Comment by jnicklas** [comment]
Note: Proper typechecking of the bundle would have prevented this issue, since a step action/assertion check currently *must* return a promise.

<img width="1034" alt="Screenshot 2020-09-23 at 12 12 39" src="https://user-images.githubusercontent.com/134/93999583-469f7b00-fd96-11ea-99d8-4ef72ecc73e0.png">

**Comment by cowboyd** [comment]
Agree, but we have to handle it both with TypeChecking and at runtime in the orchestrator. The reason is for test suites implemented in JavaScript which is what we have going on with FOLIO. We really just need to make sure that whatever garbage makes its way into the manifest doesn't cause the server to crash when we load it to harvest metadata.

**Comment by cowboyd** [comment]
Actually, I'm thinking of a separate issue, nvm. This error is being thrown on the agent.
