### ISSUE TITLE
Allow interactor locators to be regular expressions?

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#438]
Let's say you want to match on a heading that has a lot of text.

```html
<h1>"Welcome to FOLIO, the future of libraries is open"</h1>
```

If you want to select this element, there is currently only one way to do that, which is to select by the whole string:

```ts
Heading("Welcome to FOLIO, the future of libraries is open").exists()
```

This is a keyboard full, and also is brittle if we're looking for something that might change fairly often, but will still be "mostly" the same.

What about allowing the match of a locator against a regular expression instead of exact string matching. In other words, allowing us to write the forementioned as:

```ts
Heading(/^Welcome to FOLIO/).exists()
```

**Comment by pittst3r** [comment]
I think this makes sense. I was going to propose allowing a matcher function to be passed in, which could solve this problem, but that would move the job of comparing values out to the consumer.

**Comment by cowboyd** [comment]
> I think this makes sense. I was going to propose allowing a matcher function to be passed in, which could solve this problem, but that would move the job of comparing values out to the consumer.

A matcher function is compatible with this idea, and a regular expression is really nothing more than syntax for defining a matcher function. The difference is that the matcher function runs on the _locator_, not the element.

**Comment by jnicklas** [comment]
Should we remove the beta milestone from this? It doesn't seem essential to me.

**Comment by cowboyd** [comment]
I'm ok with this. I'm also going to mark it as a good first issue. Seems like it's a fairly easy one, but also not the highest priority.

**Comment by minkimcello** [comment]
@cowboyd Should this be an either-or situation so users have an option to use a regular string if they wanted to?

**Comment by cowboyd** [comment]
@minkimcello yes.

```ts
Button("Submit")
Button(/[Ss]ubmit/) should both work.
```

**Comment by jnicklas** [comment]
With the introduction of matchers this feels to me like it is no longer necessary?

**Comment by cowboyd** [comment]
Yep, We would write the original example as `Heading(matching(/Welcome to FOLIO/))`

And so it looks like @pittst3r wins the crystal ball award. From his comment on August 5th 2020:

> I think this makes sense. I was going to propose allowing a matcher function to be passed in, which could solve this problem, but that would move the job of comparing values out to the consumer.
