### ISSUE TITLE
Solid Test Bundling

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#443]
In order to make sure that we have swipe to unlock, our ability to bundle the tests and make sure that they load into the test enviroment has to be 100% bullet proof. That means that after you run `bigtest init`, but both `bigtest server` and `bigtest ci` will run without warnings, without error regardless of environment. To name just a few things:

1. If using typescript, it does not matter what their `tsconfig.json` looks like.
2. If using babel, it does not matter what their `.babelrc` looks like.
3. If using rollup, it does not matter what their 'rollup.config.js' looks like.
4. Regardless of what their `package.json` contains, or what their `yarn.lock` looks like, it will work.

We don't have an exhaustive list of issues, so we first need to identify areas where we migth fail, and then start thinking about solutions.

**Comment by cowboyd** [comment]
```ts
import { test } from "@bigtest/suite";
import { bigtestGlobals } from "@bigtest/globals";
import { App } from "@bigtest/interactor";
import localforage from 'localforage';

import { Heading, NavButton, Authenticate } from './interactors';

export default test('Basic Test')
  .step(Authenticate('diku_admin', 'admin'))
  .assertion(Heading('Welcome, the Future Of Libraries Is OPEN!').exists())
  .child('navigating to courses via the navigation bar', test => test
    .step(NavButton("Courses").click()))
  .child('the course app', test => test
         .step(App.visit('/courses')));
```

Here is an example of test suite that will bundle successfully, load successfully, but will then kill the client

```
error: String cannot represent value: [function]
    at /Users/cowboyd/Code/EBSCO/ui-courses/node_modules/@bigtest/server/dist/src/client.js:54:31
    at Generator.next (<anonymous>)
    at /Users/cowboyd/Code/EBSCO/ui-courses/node_modules/effection/dist/effection.js:1:8094
    at e.r.advance (/Users/cowboyd/Code/EBSCO/ui-courses/node_modules/effection/dist/effection.js:1:7730)
    at e.r.trapExit (/Users/cowboyd/Code/EBSCO/ui-courses/node_modules/effection/dist/effection.js:1:8056)
    at t.n.finalize (/Users/cowboyd/Code/EBSCO/ui-courses/node_modules/effection/dist/effection.js:1:5567)
    at t.n.resume (/Users/cowboyd/Code/EBSCO/ui-courses/node_modules/effection/dist/effection.js:1:4921)
    at /Users/cowboyd/Code/EBSCO/ui-courses/node_modules/effection/dist/effection.js:1:7238
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by cowboyd** [comment]
My thinking lately is that we need to make the manifest its own package that has control of dependencies, babel config, and tsconfig so that we can control every aspect of the build.

**Comment by jnicklas** [comment]
This issue doesn't really have a solid deliverable, if we want to keep it around, we should at least remove it from the beta milestone, IMO.

**Comment by cowboyd** [comment]
Nah, let's just add concrete tasks that we can have.
