### ISSUE TITLE
Better messaging for AmbiguousElementError

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#454]
When there are more than one element on the page that an interaction matches, we should somehow at least give an indication of which elements are present that are causing the ambiguity. Otherwise, you're left to resolve it yourself.

**Comment by jnicklas** [comment]
I've been thinking about this a bit, and it's actually a bit tricky. Sure, we have a list of elements which matched, but how should we actually render them in the error message? Printing the located value is useless (we know it matched), so what else should we print? The element's `outerHTML`? It's tag name and `id` if present? It's path in the DOM tree, however we would want to render it?

**Comment by cowboyd** [comment]
So in my case, there was actually a bug in my selector, and because it was not selective enough, I was matching multiple places within the same hierarchy:


n. I wouldn't have seen the error if my locator was properly implemented, so it's worth noting that one of the use-cases here is to help diagnose "bad" locator functions. Given that, I think we need to show both the matching elements and the computed locator for each.

It's tough to see how to accomplish both of these goals, but maybe we could start with one of my favorite conventions that browser developer tools have adopted which is to represent DOM element using their opening tag when printing them to the console. 


```
Modal("No records found") matched multiple elements:
`<section class="modal" data-test-search-re

**Comment by cowboyd** [comment]
So in my case, there was actually a bug in my selector, and because it was not selective enough, I was matching multiple places within the same hierarchy. I was writing an interactor for a `Pane` component 

![image](https://user-images.githubusercontent.com/4205/91469846-905d7a00-e859-11ea-883c-30a4181a1b88.png)

So that I could make assertions against the subtitle like `Pane("Courses").has({ subtitle: "0 records found"})`

My initial `Pane` interactor looked this:

```ts
export const Pane = createInteractor("Pane")({
  selector: '[class^=pane]`,
  defaultLocator: element => element.querySelector('[class^=paneTitleLabel]').textContent.trim();
});
```

However when matched against this HTML

```html
<section class="pane---1BkDa focusIndicator---2kxyF focusWithinIndicator---1-0y_" style="flex: 0 0 71.99999999999999%; left: 0px;">
  <div id="paneHeader7" class="paneHeader---2Pkws" tabindex="-1" aria-labelledby="paneHeader7-pane-title">
    <div class="paneHeaderButtonsArea---PLJbi first---2bvB8">
      <div class="paneMenu---15QaW">
        <button type="button" aria-label="Collapse Search &amp; filter pane...s0 applied filters" class="button---3dTwV interactionStyles---3DsW3 button---2s4EC boxOffsetSmall---1wMGw">
          <span class="inner---3-acC">
            <div class="display-flex---3i4Wo flex-align-items-center---2mhVR"></div>
          </span>
        </button>
      </div>
    </div>
    <div class="paneHeaderCenter---3q7C3">
      <div class="paneHeaderCenterInner---2IRDr" id="paneHeader7-pane-title">
        <h2 class="paneTitle---25LYc">
          <div class="appIcon---1l5fx small---3Lbqo icon-alignment-center---sQq84">
            <span class="icon---1xNd8" aria-hidden="true">
              
            </span>
          </div>
          <span class="paneTitleLabel---2c7PC">Courses</span>
        </h2>
        <p id="paneHeader7-subtitle" class="paneSub---3qpJT">
          <span>0 records found</span>
        </p>
      </div>
    </div>
    <div class="paneHeaderButtonsArea---PLJbi last---3ndzE">
      
    </div>
  </div>
  <div id="7-content" tabindex="-1" class="paneContent---luK4O" style="position: relative;">
    <div style="overflow: visible; height: 0px; width: 0px;">
      <div class="mclEmptyMessage---3eKyX" style="min-width: 1058px;">
        <div>
          <div class="noResultsMessage---q2iaz">
            
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
```

It actually matched against the `.pane`, the `.paneHeader`, the `.paneHeaderCenter` because each of those classes started with `pane` and had a child `.paneTitleLabel` named `Courses`, so they all had the same locator.

One of my favorite conventions adopted by browser developer tools is to represent DOM elements using their opening tags when representing them in the console. Something like:

```
Pane("Courses") matches multiple elements:
- <section class="pane---1BkDa focusIndicator---2kxyF focusWithinIndicator---1-0y_" style="flex: 0 0 71.99999999999999%; left: 0px;">
- <div id="paneHeader7" class="paneHeader---2Pkws" tabindex="-1" aria-labelledby="paneHeader7-pane-title">
- <div class="paneHeaderButtonsArea---PLJbi first---2bvB8">
- <div class="paneHeaderCenter---3q7C3"> 
- <div class="paneHeaderCenterInner---2IRDr" id="paneHeader7-pane-title">
- <h2 class="paneTitle---25LYc">
```

This would have been hugely helpful when diagnosing that the problem was that my selector was overmatching and really should have been `[class^=pane-]`

**Comment by cowboyd** [comment]
Worth also noting that if we allow composing locator functions and using interactors inside locators we could even provide more context if instead of saying

```ts
element => element.querySelector('[class^=paneTitleLabel]').textContent.trim()
```

for the locator, we somehow could delegate to the locator of nested interactor. e.g.

```ts
(interactor, locator) => interactor.find(PaneTitle(locator))
```

not sure how this would work, but something to consider.
