### ISSUE TITLE
Un-deprecate current versions of interactor, convergence, and mocha.

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#465]
Whenever you do a yarn install on a FOLIO project, you see this

```
warning @bigtest/interactor@0.7.2: Package has been deprecated and is no longer supported.
warning @bigtest/interactor > @bigtest/convergence@0.10.0: Package has been deprecated and is no longer supported.
warning @bigtest/mocha > @bigtest/convergence@1.1.2: Package has been deprecated and is no longer supported.
```

which engenders the feeling that bigtest is abandonware

We should always off deprecating until the path forward is available, and then have in the deprecation message "@bigtest/interactor 1.0 is now available. See the upgrade guide"

Let's un-deprecate these release series, until such time as we have released bigtest 1.0 and have an upgrade path.

**Comment by minkimcello** [comment]
Undeprecated `interactor`, `convergence` and `mocha`. 👌
