### ISSUE TITLE
What is up with NodeList

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#480]
When working on the `ui-courses` FOLIO test suite, @pittst3r and I ran across an issue where if we used a `NodeList` which is mutable in the context of a filter, it would not match.

https://github.com/cowboyd/ui-courses/blob/bigtest-spike/test/interactors.js#L108

Why?

**Comment by jnicklas** [comment]
Interestingly, according to MDN, the NodeList returned by `querySelectorAll` is *not* live/mutable ([source](https://developer.mozilla.org/en-US/docs/Web/API/NodeList)), but rather actually a static list of elements. This probably means that there is something else going on here.

**Comment by cowboyd** [comment]
Hmm, even though it seems like we mis-diagnosed the problem, it's encouraging since evene if it were mutable and live, then it _should_ still only be looking at it during a snapshot in time. Hopefully then we can get to the bottom of it and fix it for good rather than having to say "watch out for this gotcha" in our docs.
