### ISSUE TITLE
Unexpected Interactor AmbiguousElementError

### ISSUE THREAD

**Issue by pittst3r** [thefrontside/bigtest#482]
If I have the following markup:

```html
<div>
  <div>
    <label for="thing">Thing</label>
    <input type="text" id="thing" />
  </div>
</div>
```

This interactor will produce an `AmbiguousElementError` because both divs match:

```js
const TextField = createInteractor('text field')({
  selector: 'div',
  defaultLocator: element => element.querySelector('label')?.textContent,
  // ...
});
```

How do I create an Interactor that matches on the label text and fills in the input without getting an `AmbiguousElementError`? Does the wrapping div need some unique identifier like a `data-test-text-field` attribute?

**Comment by jnicklas** [comment]
As discussed on discord, this behavious is expected, the locator actually *is* ambiguous. A better solution in this case would be to use `input[type=text]` as the selector and have the locator use [`.labels`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/labels) to grab the label value.
