### ISSUE TITLE
`exists` and `absent` interactions should allow ambiguous matches

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/bigtest#488]
The `exists` and `absent` interactions currently use `unsafeSyncResolve` under the hood, just like actions do. However, this isn't ideal. Given the following markup:

``` html
<a href="/foo">Foo</a>
<a href="/bar">Foo</a>
```

We would expect an interactor like this to succeed:

``` typescript
Link("Foo").exists()
```

However it gets a bit murkier when we get to something like this:

``` html
<section title="Bar">
  <a href="/foo">Foo</a>
</section>
<section title="Bar">
  <a href="/bar">Foo</a>
</section>
```

``` typescript
Section("Bar").find(Link("Foo")).exists()
```

Should this pass or fail? It is imo not quite clear. My instinct is that it *should fail*, since `exists` refers to the link, and not the entire chain of interactors. But I think a case can be made for either option 🤔

**Comment by cowboyd** [comment]
My $0.02 is also that it should fail, because if you think of it not as the component parts, but about the composite interactor as a whole, what you're saying in effect is:

```ts
let LinkFooWithinSectionFoo = Section("Foo").find(Link("Foo"));
LinkFooWithinSectionFoo.exists()
```
Which is clearly false.

On the other hand:

```ts
let LinkFooWithinSectionBar = Section("Bar").find(Link("Foo"));
LinkFooWithinSectionBar.exists()
```

would not fail because such an element does exist.

**Comment by jnicklas** [comment]
@cowboyd I wrote the example incorrectly. Edited above to fix. I was asking about whether this should fail or pass:

``` typescript
Section("Bar").find(Link("Foo")).exists()
```

At first glance the answer seems to be yes, there is a after all a `Foo` link within a `Bar` section. But the tricky thing here is that the `Bar` section is ambiguous, so the question is which algorithm `exists()` should use. Basically should it allow ambiguous matches for:

1) all items in the chain.
2) for only the last item
3) for none of them

Currently the answer is (3), but IMO, the better answer is either (1) or (2), but I'm actually not sure which of those is better. I think the most intuitive answer is (1), but I'm worried that it is too permissive, so I'm leaning towards (2).

**Comment by cowboyd** [comment]
Ah, I see. Yes, in that case, I agree that the most intuitive is (1) since if you were to hide the composition behind a single interactor:

```ts
export const LinkWithinBar = locator => Section("Bar").find(Link(locator))
```

It would be very weird that:

```ts
Link("Foo").exists() 
```
is true, but the following is false

```ts
LinkWithinBar("Foo").exists() 
```
It feels dangerous to force users to hold context of how an interactor is nested in their head when parsing how the `exists()` function will behave. It's almost like we need to split this into two operators? maybe `exists()` and `unique()`? Or `exists()` and `expect()`? Or maybe using a quantifier like

```ts
// unique match, default
Link("Submit").exists()
// alias for:
Link("Submit").unique.exists()
//vs
Link("Submit").any.exists();
```

**Comment by jnicklas** [comment]
I just tried implementing option (1) and it is an absolute, total pain. It just does not mesh well at all with the way we are currently generating error messages. I'm sure we could make this work somehow, but it is likely going to make our error messages much worse than they are now.

I'm still leaning towards (2). I can totally see the argument that (1) is more intuitive, but the implementation will be extremely complicated, and it will make error messages worse across the board. I just don't think this will be a terribly common problem to make it worth it.

**Comment by cowboyd** [comment]
Is the problem that we need to represent each possible matching path to the element?

**Comment by jnicklas** [comment]
@cowboyd yes, exactly. And the worse part is that if *don't* find anything that matches, we then need to backtrack and figure out why. So not only do we need to preserve all of the possible paths, but also all of the matching information at each level, and then if we can't find anything we need to go back and figure out at which level the issue was, which might be different for different paths taken, which turns into a whole big mess when we try and render an error.

E.g. if we have `Div -> Section -> Button`, and there are two matching `Div`s, one has a `Section` but no button and the other has no `Section` and no `Button`. How would we format this error message in a way that makes sense to the user?

It makes me think of parsers where LL/LR parsers are easier to use and write, despite being more restrictive than generalized parsers, because they do not allow ambiguity in their matching, and so they can generate better error messages and prevent the user from doing silly stuff.

**Comment by cowboyd** [comment]
I see. What if we give option (2) a shot, and if it turns out to be confusing, we'll try something else?
