### ISSUE TITLE
Interactor specification types are too permissive

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/bigtest#513]
As pointed out by @dagda1.

When creating an interactor via `createInteractor`, the given options are properly type checked, but the set of options is not closed, so this is allowed, but it should not be:

``` typescript
createInteractor('foo')({ doesNotExist: "blah" });
```

**Comment by jnicklas** [comment]
Had an initial poke at this and it quickly turns into a bloodbath of type parameters. Not sure this is worth it.

**Comment by dagda1** [comment]
@jnicklas I really like the API of `createReactor` but the lack of type safety means it is very easy to introduce bugs with simple typos.

Don't write it off just yet.  Let me have a crack at it.  Might need to upgrade to typescript 4

I created [this PR](https://github.com/thefrontside/javascript/pull/16) to get the ball rolling for typescript 4 but it went quiet
