### ISSUE TITLE
Using `hasClass` with CSS Modules

### ISSUE THREAD

**Issue by cherewaty** [thefrontside/bigtest#52]
On an app using CSS Modules, what should be the strategy for using the `hasClass()` page object property?

1. Import the CSS file with the style into the page object as `styles` so you can check for `hasClass(styles.hasError, '#idThatWouldHaveError')`.

2. Modify `hasClass()` to accept a regex as the `className` - that way a class `.hasError--{hash}` can be found with `hasClass('^has-Error--.*$', '#idThatWouldHaveError')`.

Option 1 seems more bulletproof, but should page objects be dealing with CSS like that? Option 2 would be a nice option, even if it wouldn't work for apps using CSS Modules that don't leave part of the original class name.

**Comment by wwilsman** [comment]
Option 1 seems like the more proper way. I do like option 2 because that can allow you to match multiple classes and seems more robust.

I'll also introduce option 3:
```
is('[class*="has-Error--"]', '#idThatWouldHaveError')
```

**Comment by Robdel12** [comment]
I think the artifact for this ticket is we update the docs for usage with CSS guides. We can use option 1 today I believe and option 3 works for sure. 

When you import styles into a js file its basically an object with the real class name as the key & the value is the CSS module class name.

```js
// ...
import styles from 'styles.css';

@page class myPage {
  // styles --> { hasError: 'hasError--hbQY8' }
 thingHasError =  hasClass(styles.hasError, '#idThatWouldHaveError')
}
```
