### ISSUE TITLE
Better server console output

### ISSUE THREAD

**Issue by minkimcello** [thefrontside/bigtest#532]
I've come across a few inconveniences regarding the server console output while writing tests. I'm not entirely sure if they're related to the `server` itself or if it's the `bundler` or `orchestrator` but I'll list them here:

1. When there's an error from building the manifest, the errors are overwhelming to the user and it would be really nice if we could shave it down to the most essential errors. Not only is each of the individual errors long in content but they get spammed in the console. Here's a screenshot of what one of those errors looks like in the console:

![Screen Shot 2020-09-14 at 9 41 32 AM](https://user-images.githubusercontent.com/29791650/93096059-eb70d880-f671-11ea-8cbc-622d494d3348.png)

2. And when those errors are addressed, the server console doesn't refresh itself to say "everything is good now". It just stays on the error so I'm constantly wondering if there are more errors.

3. It would be nice to see how many test suites bigtest is able to detect. Sometimes in order to run a test file in isolation, I will specify the file I want in `bigtest.json` but if there's a typo, running the test command will just linger without letting the user know that there are no tests detected. It could make users jump to the conclusion that Bigtest is stalling and takes a few moments before I consider the possibility that I made a typo.

![Screen Shot 2020-09-14 at 10 03 05 AM](https://user-images.githubusercontent.com/29791650/93096415-5a4e3180-f672-11ea-8f45-4a3eb4e86763.png)

4. Related to the second point, how can we refresh the server console whenever a test file is updated? I'll run the tests, make changes to a test, save the file, re-run the test. But if that's done too quickly before the server is done refreshing, it'll run the old test suite. I've been remembering the number of steps and assertions from the previous run to confirm that bigtest ran the most updated version of my test but in cases where there are no new steps/assertions, I don't have any way of confirming if bigtest ran the newest test suite or its previous iteration. This particular issue slows down my test-writing process.
    - Again I'm not sure if this is viable but perhaps whenever the server detects a file has changed, it can update its status to "Updating..." and when finished updating it could provide a unique ID of some sort so that when I run tests in a separate terminal, it can display that ID to confirm that the test run is indeed after the refresh with the new files? 🤷

**Comment by jnicklas** [comment]
@minkimcello great feedback, thanks!

I have a PR open to address (1) and (2), see #536 

(3) will be covered by fixing #386, which I'm currently working on

(4) will be addressed by fixing #279, which @cowboyd and I are also currently working on
