### ISSUE TITLE
Run agent test suite in Firefox

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#533]
We don't currently run our agent tests in firefox. This would be a very simple way to check that we won't have catastrophic failures on that platform.

**Comment by cowboyd** [comment]
@jnicklas I've noticed that while Firefox consistently reproduces the issue with the log events, it _does_ sometimes occur in CI on chrome https://github.com/thefrontside/bigtest/runs/1115552098?check_suite_focus=true#step:6:58

It looks like sometimes the log events and step events arrive in different order?

<blockquote><img src="https://repository-images.githubusercontent.com/100052766/a3090380-83ce-11ea-9e4b-1d0396ecd24b" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/thefrontside/bigtest">thefrontside/bigtest</a></strong></div><div>Tests that speed up development, not slow it down. Contribute to thefrontside/bigtest development by creating an account on GitHub.</div></blockquote>

**Comment by cowboyd** [comment]
Here's another example https://github.com/thefrontside/bigtest/runs/1128974253?check_suite_focus=true#step:6:58

<blockquote><img src="https://repository-images.githubusercontent.com/100052766/a3090380-83ce-11ea-9e4b-1d0396ecd24b" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/thefrontside/bigtest">thefrontside/bigtest</a></strong></div><div>Tests that speed up development, not slow it down. Contribute to thefrontside/bigtest development by creating an account on GitHub.</div></blockquote>

**Comment by jnicklas** [comment]
This is done, except we run the CLI tests in firefox now
