### ISSUE TITLE
Fully restart orchestrator in those tests that need it.

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/bigtest#545]
We have some "big" tests which test the entire orchestrator as part of the server test suite, these tests use `startOrchestrator`. Currently we do some hackery to keep the orchestrator running and reuse it for multiple tests. Given that we don't have any safe way of restarting the orchestrator at the moment, and the fact that our orchestrator is now very stateful, this seems a bit unsafe. Given that we already do some manual juggling of state [like this](https://github.com/thefrontside/bigtest/blob/6e2e50f6ff62f06c8abd20c71726da1ceb6aef8a/packages/server/test/helpers.ts#L86), we should probably just start a new orchestrator for each test. This is now much faster than it used to be anyway, and it's better to have a suite which is slow and correct, rather than fast and broken.

**Comment by cowboyd** [comment]
I also think that by making the orchestrator "readiness" not a single thing, we can significantly speed up time-to-usable for many specific use cases which, if you're testing just about anything except test bundling, is a matter of milliseconds.

As we move more and more ready state to the atom,  then the test cases can use it to compose their own idea of what they need to be ready. For example: only need to talk to the command server and don't care when the other services come online? Add

```ts
await run(atom.once(state => state.commandServer.ready));
```

**Comment by jnicklas** [comment]
This is done
