### ISSUE TITLE
Excessively long interactor error reporting

### ISSUE THREAD

**Issue by minkimcello** [thefrontside/bigtest#553]
Currently when I have an interactor for which there are multiples, Bigtest will make a suggestion to help me fix my test suite. Although is helpful in most cases, I think it might be helpful to have a conditional to have a more general error report when the suggestions exceed a certain number. 

Examples 1 is from a real use case where it spammed the console so much that I couldn't actually scroll up to see which interactor it was referring to. Examples 2 and 3 are what I replicated by having a very vague interactor:

Example 1:
![Screen Shot 2020-09-21 at 12 05 39 PM](https://user-images.githubusercontent.com/29791650/93801888-b71c8f80-fc10-11ea-9401-4880c9abcc73.png)

Example 2:
![Screen Shot 2020-09-21 at 1 46 04 PM](https://user-images.githubusercontent.com/29791650/93801962-d3b8c780-fc10-11ea-9df5-c4e009df02e6.png)

Example 3:
![Screen Shot 2020-09-21 at 1 43 20 PM](https://user-images.githubusercontent.com/29791650/93801970-d61b2180-fc10-11ea-9d68-80416ffe2398.png)

**Comment by jnicklas** [comment]
Thanks for the great report @minkimcello. These errors are pretty funny. Building in some reasonable caps seems pretty like a great idea.
