### ISSUE TITLE
Migrate Atom to monocle-ts

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#559]
Ramda lenses only abide by the lens laws if you consider their own `equals` function to be the only definition of equality. However, if you throw `===` into the mix, they violate it pretty handily. Monocle does not which makes our life eaiser when it comes to publishing different versions of an Atom's state since we can just check if it is a reference to the same value.

Therefore, for performance and correctness reasons, we'd like to migrate to monocle-ts.

**Comment by jnicklas** [comment]
This is done and atom has moved to effection
