### ISSUE TITLE
Tests on Mac intermittently fail when installing dependencies

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/bigtest#562]
Getting these errors reasonably frequently. Oddly, this only seems to happen on the Mac actions, not on Ubuntu.

<img width="923" alt="Screenshot 2020-09-24 at 14 04 41" src="https://user-images.githubusercontent.com/134/94142711-0102b100-fe6f-11ea-9be1-3887e6393fcd.png">

**Comment by cowboyd** [comment]
Maybe the cache is not in the same place as on ubuntu? It seems like it shouldn't be trying to download it at all.

**Comment by jbolda** [comment]
I don't know where Mac drops it offhand, but that makes sense to me. It may be worth dynamically grabbing it like this:
https://github.com/actions/cache/blob/master/examples.md#node---yarn

<blockquote><img src="https://avatars2.githubusercontent.com/u/44036562?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/actions/cache">actions/cache</a></strong></div><div>Cache dependencies and build outputs in GitHub Actions - actions/cache</div></blockquote>

**Comment by cowboyd** [comment]
Nice find @jbolda! I don't know if anybody has time to get to this today, but otherwise, we should probably make the check optional in the mean time.
