### ISSUE TITLE
Are locators redundant?

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/bigtest#573]
I've been working on some built in interactors, and one thing that struck my is that custom locators feel kind of redundant to me, with some simple changes we could replace them with filters entirely. Let's look at an example:

This is how we would use a custom locator today:

``` typescript
Button.byId('my-button').click()
```

We already allow the locator to be omitted, which will find any element which matches the selector. So for example, this will match any button, regardless of its text:

``` typescript
Button().click()
```

If we combine this features with passing filters, then we can emulate the behaviour of a custom locator:

``` typescript
Button({ id: 'my-button' }).click()
```

This should match any button which has the id `my-button`, this is exactly the same as the custom locator.

Currently this is not supported, filters cannot be passed if the locator is omitted, but IMO this *should* be supported, and if we do, we might as well get rid of custom locators entirely.

There might be some slight complications with generating error messages, but I think overall this is a worthwhile simplification.

The nice effect of this is that it will simplify the interactor types quite a bit :)

Thoughts, @pittst3r @minkimcello @cowboyd?

**Comment by minkimcello** [comment]
I was curious about this too and was wondering what the use case was for filters vs locators. It would make it much simpler to explain how to use interactors if we removed the locator in my opinion.

**Comment by cowboyd** [comment]
@jnicklas @minkimcello I felt this pain too, but didn't have a word for it until I read this. Really locator just becomes a default filter?

```ts
await Button("Submit").exists() ===
await Button({ textContent: "Submit" }).exists() === 
await Button().exists({ textContent: "Submit"})
```

I like it a lot 👍

**Comment by jnicklas** [comment]
@cowboyd I just tried implementing it this way, and there are a number of challenges with getting the types right. Chief among which is that filter parameters can currently be any type, including objects, and so distinguishing `Button({ text: "foo" })` from `Button({ someFilterParam: "foo" })` is basically impossible. So I think we will want to preserve the property that the first argument must be a string, and then we can't just make it a filter. Also it is quite challenging (though maybe not impossible) to lift the name of the default value from a value space to the type space.
