### ISSUE TITLE
Should we work around React monkey-patching `HTMLInputElement.value`

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#596]
While assembling a demonstration for BigTest using the [realworld e2e example](https://github.com/anishkny/realworld-e2e-test) I ran into a situation where React was not becoming aware of changes that the interactor was making in the DOM. While the typed text was successfully written to the input field, the application was not aware of it, and so was acting like the text field was blank.

This issue is documented here, https://github.com/cypress-io/cypress/issues/536, and we were able to apply the workaround [alluded to](https://github.com/cypress-io/cypress/issues/536#issuecomment-311694226) here. The workaround worked great, but the question is, do we account for it in the core interactors?

It was a surprising result, and definitely would have been difficult to track down without a core contributor at hand. Given that, it could be a real problem if there are a large number of applications on which our interactors won't work. React is a _very_ popular framework, and so we have to do some sort of estimation about which versions are effected so that we can understand what size of risk are we talking about. We should find out:

- [ ] Which versions of react behave in this way on a point release by point release basis
- [ ] What percentage of apps out there are within that range
- [ ] How to help anybody encountering this problem detect it, and overcome it (including just fixing it for them)

**Comment by cowboyd** [comment]
I believe we're seeing this in a React `v16.13` app created only a few months ago.

**Comment by jnicklas** [comment]
Since we've already hit this *twice* now, it seems to a pretty commonly occuring problem. As much as this is a disappointing technical recision by React, we probably need to live with it, and React is so big that we can't afford to ignore it. I think we should add a fix for it.

**Comment by cowboyd** [comment]
Here is the workaround that @GulinSS came up with:

```ts
export const TextField = createInteractor<HTMLInputElement>('text field')({
   selector: 'input[class^="ant-input"]',
   defaultLocator: element => element.labels?.[0]?.textContent || '',
   actions: {
     fill: perform((element, value) => {
       let descriptor = Object.getOwnPropertyDescriptor(element, 'value');
       // eslint-disable-next-line @typescript-eslint/ban-ts-ignore
       // @ts-ignore
       if (descriptor) delete element.value;
       element.value = value;
       element.dispatchEvent(new Event('input', { bubbles: true, cancelable: true }));
       element.dispatchEvent(new Event('change', { bubbles: true, cancelable: true }));
       if (descriptor) {
         Object.defineProperty(element, 'value', descriptor);
       }
     })
   }
 });
```

Which looks very much like it is solving the same problem.

Here's what I ended up implementing for the demo which leaves the monkey patch in place, but circumvents it by using the HTMLInputElement prototype for the purpose of simulating the browser event:

```ts
function setValue(element: HTMLInputElement, text: string) {
  let InputElement = element.ownerDocument.defaultView?.HTMLInputElement || window.HTMLInputElement;
  let prop: PropertyDescriptor = Object.getOwnPropertyDescriptor(InputElement.prototype, 'value');
  prop.set.call(element, text);
}
```
