### ISSUE TITLE
Should we really be checking app reachability so often?

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/bigtest#642]
I don't think 100ms is an appropriate interval to check app reachability. If we do this at all, after the app has started, which IMO is pretty questionable, we should at least decrease the interval quite significantly. Something like every 5s seems much more reasonable to me.

**Comment by cowboyd** [comment]
100ms does seem excessive after startup. What's reasonable is going to be different from app to app. For a forms over html app where serving your index can involve a lot of computation, 100ms is totally insane, but for an SPA which is basically a static html file, it doesn't matter as much.

The trade-offs are the ability to quickly react to app reachability on one hand vs hammering IO/CPU on the other.
