### ISSUE TITLE
Helper for checking every member of a collection against a predicate

### ISSUE THREAD

**Issue by keathleydavidj** [thefrontside/bigtest#65]
It would be nice to have a way to check every member of a collection against a predicate that returns the results `&&`ed together.

Given a collection such:
```
  items = collection($selector, {
    isSelected: hasClass('selected', $child)
  });
```

The ability to add something like the following property would be boss:
```
  allItemsSelected = all(this.items(), item => item.isSelected);
```

**Comment by Robdel12** [comment]
We should also implement `some` & `none` along with this

**Comment by Robdel12** [comment]
smh. I really wanted you to work move bot.

**Comment by dessant** [comment]
@Robdel12, your friendly bot maintainer here, got tipped off by Sentry. :yum: 

You have to install the GitHub app for the target repo too, otherwise the bot would be opened up for proxy spamming.

**Comment by Robdel12** [comment]
Hey @dessant! :p I _think_ its configured correctly: 
<img width="960" alt="screen shot 2018-04-15 at 2 03 32 pm" src="https://user-images.githubusercontent.com/2072894/38782226-f2790838-40b5-11e8-8ad1-812a4e5b2036.png">

I figured it might have been a propagation issue? I also added a `.github/move.yml` to the repo hoping that was the missing piece too.

**Comment by dessant** [comment]
Your installation is correct, I was able to reproduce the bug, it seems there is a hiccup while moving issues between orgs. I'll look into it and update you here.

**Comment by Robdel12** [comment]
No rush! Thank you for taking a look :D

**Comment by dessant** [comment]
@Robdel12, a fix was just released, moving issues between different orgs should now be possible. Thanks for surfacing the bug!
