### ISSUE TITLE
Including declaration for a non-export (Cypress + Typescript)

### ISSUE THREAD

**Issue by minkimcello** [thefrontside/bigtest#685]
Related to #672
## Goal
I would like for the `interactor` package to compile and include the declaration of the Cypress commands:
```js
// interactor/dist/types/integrations/cypress.d.ts

declare namespace Cypress {
  interface Chainable<Subject> {
    do(interaction: any): Chainable<Subject>;
    expect(interaction: any): Chainable<Subject>;
  }
}
``` 
Since we're importing the Cypress commands into `packages/interactor/src/index.ts`, they're being loaded up as a side effect when any of the interactors are imported. This allows Cypress-users to import interactors and use them right away without having to go through any other configuration process.

## Problems
1. Whenever the namespace is exported, the commands are no longer recognized in the tests (in one of my personal repositories that's consuming the preview package from the PR). Is it possible to compile the declaration exactly as shown above?
2. These namespaces can't be declared with ES imports and thus preventing me from importing `Interaction` and `ReadonlyInteraction` types so that I can type out the commands like so: `do(interaction: Interaction<void> | Interaction<void>[]): Chainable<Subject>;` which makes me wonder if declaring a namespace is the wrong approach.

**Comment by cowboyd** [comment]
@dagda1 do you know of a clean way to do this?

**Comment by dagda1** [comment]
@cowboyd @minkimcello do you have something failing that I can look at?  

Where does the `.d.ts` file get loaded?

Did you try declaring `Cypress` in the global namespace.  I seem to remember doing this before :

```ts
declare global {
  namespace Cypress {
    interface Chainable<Subject> {
      do(interaction: any): Chainable<Subject>;
      expect(interaction: any): Chainable<Subject>;
    }
  }
}
```

Apologies, for the late answer, I did not realise this was assigned to me.
```

**Comment by minkimcello** [comment]
Resolved 🎉
