### ISSUE TITLE
Workflow suggestion: run macOS and windows tests on release PRs only

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/bigtest#695]
We've been struggling with balancing our development workflow. We want to work quickly, have a fast feedback loop, but we also want to deliver solid software. Since the stability and performance of the macOS and windows test actions on GitHub has been disappointing, maybe we could try running these actions on the release PRs only. This way we'd ensure that we don't slow down our development workflow too much, while still ensuring that our releases work on all platforms that we support.

**Comment by dagda1** [comment]
Definitely agree with this.  I think we will always have a bit of bother when the chromedriver updates and the VM images lag behind.  I've had this in CI environments a lot.

**Comment by cowboyd** [comment]
We also discussed moving the actual checks to CircleCI

**Comment by minkimcello** [comment]
We could also run linux tests on every PR and include windows tests only for the release PR?

And can I go ahead and implement this? Because playing whac-a-mole with tests in PR is not fun.

**Comment by cowboyd** [comment]
Painful as it might be, we have to find the way to make our tests more reliable. Only running them on release PRs would just be sweeping things under the rug. If we think that it's frustrating to have flaky windows tests on a PR, it's gonna feel way worse if that same flake is hiding there just waiting to block a release.

**Comment by minkimcello** [comment]
So then should we go ahead and close this issue?

**Comment by dagda1** [comment]
I think we should get to the bottom of why they are flaking rather than saving up the agony.

**Comment by jnicklas** [comment]
With the switch to CircleCI, our tests are now reliable and reasonably fast. Let's close this.
