### ISSUE TITLE
Review & iterate on the locators-filters-actions page

### ISSUE THREAD

**Issue by jenweber** [thefrontside/bigtest#705]
To me, this page's draft still feels a little too vague to be useful beyond the initial learning experience. It could use some more real-world context and explanation.

**Comment by cowboyd** [comment]
Key points to include based on my session with @jbolda yesterday:

Relationship between selector, locator and filters is particularly important.

`selector` -> used to find a  set of candidate nodes for an interaction.
`locator` -> **user readable** string that identifies a node from the list of candidates. It is important to think about this in the way a user would.
`filter` -> some value that can be matched against to _narrow_ the list of candidate nodes.

other points:

* all nodes selected by `selector` should represent the same starting point in a DOM hierarchy
* the locator, plus all filters and actions will be relative to 
* it is A-OK to dig into the DOM relative to the that base node. E.g. If you have a component whose current HTML looks like:

```html
<div class="text-field">
  <label for="password-field">Password</label>
  <input type="text" id="password-field">
  <span class="errors">Must be at least 8 characters</span>
</div>
```

It is encouraged to dig into to get your locator and filters:

```ts
export const TextField = createInteractor("text field")({
  selector: 'div.textfield',
  locator: element => element.querySelector('label')?.textContent,
  filters: {
    errorText: element => element.querySelector('.errors')?.textContent
  }
});
```

thus allowing you to say:

```ts
await TextField("Password").fillIn('too-short');
await TextField("Password").has({ errorText: "Must be at least 8 characters" });
```

**Comment by jenweber** [comment]
Closed by https://github.com/thefrontside/bigtest/pull/798
