### ISSUE TITLE
Add a more complex example to the Quick Start

### ISSUE THREAD

**Issue by jenweber** [thefrontside/bigtest#713]
Could show combining them into one function:

```javascript
async function Login(username, password) {
  await Input("username").fillIn(username);
  await Input("password").fillIn(password);
  await Button("Sign In").click();
  await Heading("My Account").exists();
}
```

This is simple, but doesn't showcase interactors. Can we do something with an accessibility test? Maybe it's a new interactor that someone can copy-paste and we explain it in "how to write your own"

**Comment by minkimcello** [comment]
Added a date picker example from a pretend-airline web app
