### ISSUE TITLE
Does your beta version support parallel executions and headless mode?

### ISSUE THREAD

**Issue by 4l1ce** [thefrontside/bigtest#732]

**Comment by minkimcello** [comment]
@4l1ce Yes, we have headless browsers available for firefox and chrome. You just need to configure your `bigtest.json` like this:
```
{
  "app": {...},
  "testFiles": [...],
  "launch": [
    "chrome.headless",
    "firefox.headless"
  ]
}
```
If you specify multiple browsers as shown above, they will run in parallel (so you would _not_ have to wait for chrome to finish running in order for firefox tests to start), but the tests themselves (within each browser) will run one after the other.
