### ISSUE TITLE
Links are difficult to click in a quote

### ISSUE THREAD

**Issue by minkimcello** [thefrontside/bigtest#751]
This might be a docusaurus issue, I'm not sure. Links are fine in regular text but if we have a link inside of a quote:

```md
> [hello](google.com)
```

... the clickable area is limited. And that area changes depending on the responsive size of the website. Below are screenshots with the clickable area highlighted in green and unclickable in red:

![Screen Shot 2020-12-23 at 3 33 17 PM](https://user-images.githubusercontent.com/29791650/103035438-4d749000-4535-11eb-9287-5d5094494758.png)
![Screen Shot 2020-12-23 at 3 33 29 PM](https://user-images.githubusercontent.com/29791650/103035439-4e0d2680-4535-11eb-9f12-fcb98a2567f8.png)

See example from the preview build: https://deploy-preview-662--bigtest.netlify.app/bigtest/docs/interactors/

**Comment by jorgelainfiesta** [comment]
The problem was caused by some weird padding I had added to the anchor link, that was overflowing. So the problem was not the link in the quote, but a link before a heading.
