### ISSUE TITLE
Spacing tweaks for headings

### ISSUE THREAD

**Issue by minkimcello** [thefrontside/bigtest#752]
When we have a H2 followed directly by H3, there's an undesirable gap.

Example of H2 followed by text:
![Group](https://user-images.githubusercontent.com/29791650/103035648-c2e06080-4535-11eb-8d91-2153d4740e81.png)

Example of H2 followed by H3:
![Group 2](https://user-images.githubusercontent.com/29791650/103035660-c96ed800-4535-11eb-8f70-9c3be27790c6.png)

Live example from netlify preview: https://deploy-preview-662--bigtest.netlify.app/bigtest/docs/interactors/

**Comment by jorgelainfiesta** [comment]
Fixed on #746
