### ISSUE TITLE
Add more details to the sample app's README

### ISSUE THREAD

**Issue by jenweber** [thefrontside/bigtest#790]
When someone goes through the Interactors tutorial, they may want to push their work up to GitHub. It would be great if the README linked to the docs for Interactors and Bigtest, and included the tagline for the project so that people know what the repo is, even if the user doesn't fill it out themselves.

**Comment by minkimcello** [comment]
> included the tagline for the project so that people know what the repo is, even if the user doesn't fill it out themselves

Do you mean a better description in `package.json`?

**Comment by jenweber** [comment]
No, I’m thinking of adding to the readme. Something like this could go under the first heading:

> This is a sample app that shows how ?[BigTest]() and [Interactors] can be used to do xzy. To create your own sample app, check out the quickstart at....

That language should borrow from the descriptions on the home pages for BigTest and interactors.
