### ISSUE TITLE
Group common property helpers

### ISSUE THREAD

**Issue by wwilsman** [thefrontside/bigtest#80]
While working with interaction page objects, I'm seeing stuff similar to this a lot:

```javascript
hasField = isPresent('input[data-test-field]');
focusField = focusable('input[data-test-field]');
fillField = fillable('input[data-test-field]');
blurField = blurable('input[data-test-field]');
```

What if we simplified that with a single property helper?

```javascript
field = input('input[data-test-field]');
```

That has a predetermined set of properties...

```javascript
page
  .field.focus()
  .field.fill('value')
  .field.blur()
```

We could do something similar with other properties as well.

```javascript
error = element('[data-test-error]');
```

...

```javascript
expect(page.error.exists).to.be.true
expect(page.error.text).to.equal('some error')
```

And maybe even a way to compose these common properties?

```javascript
field = element('[data-some-thing]').focusable().blurable().fillable()
```

**Comment by Robdel12** [comment]
Just sayin' `field = input('input[data-test-field]');` is an excellent place to do #73

**Comment by wwilsman** [comment]
I thought of that too. We could make use of composable convergences for these. An `input` convergence would do proper input validations, then the `fill`, `focus`, `blur`, etc, convergences are just chained from that initial one.
