### ISSUE TITLE
tsconfig option not being defined when using bigtest inside a monorepo

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#800]
An attempt was made by backstage developers at spiking a bigtest implementation (https://github.com/backstage/backstage/tree/59c234ed2ed3254164defcd8677170bee7a269f9). However, they quickly ran into a bundling issue where the default export of the testcase was not being included in the built manifest.

As a result, the manifest builder receives this error when trying to evaluate the manifest:

```
[manifest builder] build error:
Cannot read property 'map' of undefined
```

This is caused by the default export not being present. The test module looks like this:

```js
    var bigtest = /*#__PURE__*/Object.freeze({
        __proto__: null
    });
```
> Note: The module is named `bigtest` because in the example repo, the test case is in `src/bigtest/index.ts`. I tried changing the name of the test module and still encountered the same issue.

When it should look like

```js
    var bigtest = /*#__PURE__*/Object.freeze({
        __proto__: null,
        'default': the_actual_testcase
    });
```

This was tracked down to the `options.tsconfig` being undefined and so as a result not only was the bundle malformed, but also the entire monorepo was compiled in the `.bigtest/manifest/build` directory.

We need to make sure that we have a valid tsconfig when compiling typescript, and that we fail if one cannot be resolved, or worse if it resolves to a tsconfig in the root directory.

Reproduce
========

```
$ git clone https://github.com/backstage/backstage.git
$ cd backstage
$ git checkout 59c234ed2ed3254164defcd8677170bee7a269f9
$ yarn install
$ cd packages/e2e-test
$ yarn bigtest server
```

**Comment by cowboyd** [comment]
See 

discord: [discord://ptb.discord.com/channels/700803887132704931/700804158172954794/804920728884871168](discord://ptb.discord.com/channels/700803887132704931/700804158172954794/804920728884871168)
or discord web: https://ptb.discord.com/channels/700803887132704931/700804158172954794/804920728884871168

for the original conversation and debug session

<blockquote><img src="https://ptb.discord.com/assets/ee7c382d9257652a88c8f7b7f22a994d.png" width="48" align="right"><div><img src="/assets/07dca80a102d4149e9736d4b162cff6f.ico" height="14"> Discord</div><div><strong><a href="https://ptb.discord.com/channels/700803887132704931/700804158172954794/804920728884871168">Discord - A New Way to Chat with Friends & Communities</a></strong></div><div>Discord is the easiest way to communicate over voice, video, and text.  Chat, hang out, and stay close with your friends and communities.</div></blockquote>

**Comment by cowboyd** [comment]
Worth mentioning that setting the `tsconfig` option in `bigtest.json` or passing the `--tsconfig` cli option did _not_ fix the error. Only monkey-patching the call to `createManifestBuilder` and passing an absolute path to a `tsconfig` actually worked.

**Comment by dagda1** [comment]
the option is not getting passed through from orchestrator

```ts
  yield fork(createManifestBuilder({
    watch: options.project.watchTestFiles,
    atom: options.atom,
    srcPath: manifestSrcPath,
    distDir: manifestDistDir,
    buildDir: manifestBuildDir,
  }));
```

**Comment by cowboyd** [comment]
@dagda1 So how was this ever working?

**Comment by dagda1** [comment]
> @dagda1 So how was this ever working?

because we have both `tsconfigDefaults` and `tsconfigOverride` set in `bundler.ts`.

```ts
      typescript({
        tsconfig: bundle.tsconfig,
        tsconfigDefaults: defaultTSConfig(),
        tsconfigOverride: {
          compilerOptions: {
            module: "ESNext",
          }
```

that is like an in-memory tsconfig that seems to be enough.  

```ts
defaultTSConfig()
```
That resolves to pretty much what the tsconfig that `bigtest init` creates.
