### ISSUE TITLE
Implementing integrations for CI without mudding up the lock file

### ISSUE THREAD

**Issue by minkimcello** [thefrontside/bigtest#814]
I remember now why I piggybacked integrations' `install` and `prepack` scripts to the main monorepo. It was for the preview and release workflows. Those workflows only run `yarn install` and `yarn prepack` at the root and do not have options to run specific commands inside the individual directories of packages.

We're trying to avoid putting it into the current workspace to separate the dependencies from `yarn.lock`.

**Comment by jnicklas** [comment]
Hmm, I see. Can we add `yarn install:integrations` and `yarn prepack:integratrions` to those workflows to make that work?

**Comment by minkimcello** [comment]
@jnicklas Oh yes! We can. 😄
