### ISSUE TITLE
Documentation - show using `is` in BigTest

### ISSUE THREAD

**Issue by jenweber** [thefrontside/bigtest#817]
This could be part of a cookbook or collection of test examples.

Initially, I was writing my assertions like this:

```js
.assertion(
    TextField('Last name', {focused: true}).exists()
)
```

I learned that I could instead do the following, which reads more nicely:

```js
  .assertion(
    TextField('Last name').is({focused: true})
  )  
```

This is also a learning opportunity about how these selectors and assertions work. In example number 1, the assertion is true if there is at least one element matching the selector. There could be many. In example number 2, BigTest will throw if you try to call `is` on an array of elements. There can only be one result for the test to pass.

**Comment by cowboyd** [comment]
@minkimcello Is this addressed sufficiently by the changes you just put in relating to `is()` and `has()` ?

**Comment by minkimcello** [comment]
Yes and we also already explain the difference between `exists()` and `is()/has`
