### ISSUE TITLE
Documentation - explain better what goes into `createInteractor`

### ISSUE THREAD

**Issue by jenweber** [thefrontside/bigtest#819]
In [Write your own](https://frontside.com/bigtest/docs/interactors/write-your-own) interactor docs, we show using createInteractor, but we do not explain the string arg that it takes.

We should say that you can put anything you want for the string, and show how it is presented in the error messages. The aim is to make failures more readable and customizable.

**Comment by minkimcello** [comment]
I think this has been resolved already?

![Screen Shot 2021-05-10 at 9 02 58 AM](https://user-images.githubusercontent.com/29791650/117663332-8f157880-b16e-11eb-946a-3ab9971c3e28.png)
