### ISSUE TITLE
Documentation - Show both JavaScript and TypeScript in JS examples

### ISSUE THREAD

**Issue by jenweber** [thefrontside/bigtest#823]
Some of the examples present in the Interactors docs do not work in the sample app because it does not use TypeScript. For example:

```
import { Button, createInteractor } from 'bigtest';

export const Form = createInteractor<HTMLFormElement>('form')({
  selector: 'form',
  ....
```

A  new learner has to modify the code before it can be used. Since BigTest provides full TypeScript support, we should show TypeScript by default, but also have a tab for JavaScript.

@cowboyd @minkimcello what do you think of this idea?

**Comment by jorgelainfiesta** [comment]
Should we change the demo app to be written in typescript instead? Or only use Javascript through all the examples, and add a doc page about typescript support?

My concern is that having both tabs will imply maintaining twice as many code snippets, which can be more prone to error and imply more work when updating the docs. Plus, I don't know to what extend the difference is so great that we have to present both cases at all times.

**Comment by minkimcello** [comment]
I agree that having both wouldn't be so great. But I'm thinking maybe we can stick to Javascript instead of Typescript as it'll be more inclusive for both crowds. People who use Typescript won't have too much trouble typing the interactors.

**Comment by jenweber** [comment]
I like the idea of showing just JavaScipt, if we need to choose one. It removes a barrier for the average developer.
