### ISSUE TITLE
Website newsletter sign up form padding

### ISSUE THREAD

**Issue by minkimcello** [thefrontside/bigtest#855]
In both desktop and mobile format, there seems to be padding missing from the newsletter sign up form:

## Desktop
![Screen Shot 2021-02-10 at 10 30 49 AM](https://user-images.githubusercontent.com/29791650/107532353-d306da80-6b8b-11eb-9489-ecbc1e79f3b1.png)
- Join our newsletter image is cropped
- I think this section needs a bit more padding on the bottom so that it's more or less proportional to the rest of the page

## Mobile
![Screen Shot 2021-02-10 at 10 31 14 AM](https://user-images.githubusercontent.com/29791650/107532363-d4380780-6b8b-11eb-8a7a-169aa3676ca3.png)
- Missing left/right padding

**Comment by jorgelainfiesta** [comment]
Fixed on #861
