### ISSUE TITLE
Make it easier to find BigTest Architecture section

### ISSUE THREAD

**Issue by taras** [thefrontside/bigtest#880]
## Context

I'm talking to people about BigTest and the Architecture of BigTest is an important part of these conversations.
It would be helpful to me if it was easier to find the Architecture page from [BigTest website](https://frontside.com/bigtest/interactors).

## Possible Solution

Add a link to the Architecture page in the footer under the Platform column.

**Comment by jorgelainfiesta** [comment]
The link in the footer works for me; I wouldn't put it on the header. We also have to update "Platform" to use "Runner" everywhere, I imagine making that difference is important for the conversations you're having at the moment. I'll make a quick PR for this now.

**Comment by minkimcello** [comment]
> The link in the footer works for me; I wouldn't put it on the header. We also have to update "Platform" to use "Runner" everywhere, I imagine making that difference is important for the conversations you're having at the moment. I'll make a quick PR for this now.

@jorgelainfiesta I think he's talking about https://frontside.com/bigtest/docs/platform/architecture and not https://frontside.com/bigtest/platform, right? @taras

**Comment by taras** [comment]
@minkimcello Yes, I need the architecture page that you linked

**Comment by minkimcello** [comment]
@taras @jorgelainfiesta Does it make sense for the architecture page to be under bigtest/docs/runner? Or is it just there temporarily because we don't have much else for the runner docs at the moment? Because the architecture page seems more like a `why/what` whereas everything else in the docs is `how`.
