### ISSUE TITLE
Don't include the shell prompt in "Copy" links for guides

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#883]
When following the installation process in our guides in #882 @zburke noted that the "copy" links to copy commands included the shell prompt, which is not super useful since you end up with a double shell prompt when you try to use it.

In other words, in the display `$ npm install bigtest --save-dev`, the string that should be copied is just the command itself:

```
npm install bigtest --save-dev
```

not the command plus shell prompt.

```
$ npm install bigtest --save-dev
```

**Comment by jnicklas** [comment]
Can we just get rid of the leading `$`? Including it in the shell prompt is just a convention anyway. It use to be to distinguish from running as root using `su` where it would show a leading `#`, but no one ever does this these days anyway. My prompt does not include the `$` at all for example:

<img width="393" alt="Screenshot 2021-03-04 at 09 50 23" src="https://user-images.githubusercontent.com/134/109937308-0f32e400-7ccf-11eb-8448-757f50868185.png">
