### ISSUE TITLE
Including both yarn and npm lock files in the sample app

### ISSUE THREAD

**Issue by minkimcello** [thefrontside/bigtest#889]
In the sample app I've been including both `yarn.lock` and `package-lock.json` files so that people who want to try out `bigtest-sample` will have the appropriate dependency versions regardless of whether they use `yarn` or `npm`. This _feels_ unconventional?

I know we're planning on migrating to NPM eventually (issue #681) but assuming it's okay to have both `yarn.lock` and `package-lock.json` would the full migration to npm mean we get rid of `yarn.lock`?

**Comment by cowboyd** [comment]
@minkimcello probably? Although if we want to keep supporting yarn (doubtful) then we can keep it as long as we do.
