### ISSUE TITLE
Rename the format function for matchers

### ISSUE THREAD

**Issue by minkimcello** [thefrontside/bigtest#906]
From a discussion in [PR #902](https://github.com/thefrontside/bigtest/pull/902):

> is `format` only used to format the error message? if so can we name it more explicitly like `formatErrorMessage`? format reads a bit confusing imo because it is also makes me think that I'll use format to check a value complies with a format or something like that

I think we could call it `error()` or `errorMessage()`.

**Comment by cowboyd** [comment]
> I think we could call it error() or errorMessage().

It isn't just an error message, it's also used in locators:

`HTML(including("Hello World")).click()`:

```
couldn't find html element including "Hello World"
did you mean one of:
Hello Mom
Hello Planet
Hello Universe
```

In that case, is the string `including "Hello World"` really an error message even though it appears inside an error message?

Also, in our [inspector](https://github.com/thefrontside/bigtest/pull/903) These could appear matchers that you are just evaluating to play around, and we'd want to render them `html including "Hello World"` and there would be no error message at all.

**Comment by minkimcello** [comment]
@cowboyd Oh I see. Then maybe `description()` as you suggested would be most appropriate
