### ISSUE TITLE
Page.visit() doesn't reload url with changed hash part only

### ISSUE THREAD

**Issue by wKich** [thefrontside/bigtest#936]
For example
```ts
export default test('Foo')
  .step(Page.visit('/#/posts'))
  .step(Page.visit('/#/login')) // <= Failed by timeout
  .assertion(Page.has({ url: including('/#/login') }))
```
The second step failed by timeout because the test iframe source URL isn't changed and only the hash part is changed and the load event isn't triggered.

Refs 
- https://github.com/marmelab/react-admin/blob/master/cypress/integration/auth.js#L15-L17
- https://stackoverflow.com/questions/21893361/force-iframe-to-reload-document-when-only-src-hash-changes

**Comment by wKich** [comment]
As a proposal
```ts
const [pathname = '', hash = ''] = path.split('#');
url.pathname = pathname;
url.hash = hash;
if (hash) url.searchParams.set('bigtest', String(Date.now()));
```
instead of https://github.com/thefrontside/bigtest/blob/d85e5e952926a533c98d177b560c7a998ca597ef/packages/interactor/src/page.ts#L26

**Comment by cowboyd** [comment]
@wKich this could work, can we make the scheme specific to the page interactor, and also monotonically increasing, e.g. `bigtest-page-number=2`, `bigtest-page-number=3`, etc...?

**Comment by wKich** [comment]
@cowboyd what do you mean in scheme specific?

**Comment by cowboyd** [comment]
Sorry, what I meant was that the `bigtest` parameter is to big, let's scope it to the page interactor, so instead of `?bigtest=`, `?bigtest-page-interactor-number=3`

**Comment by wKich** [comment]
Ok :)
