### ISSUE TITLE
Side-effects in hooks not contributing to individual test time

### ISSUE THREAD

**Issue by robbiepitts** [thefrontside/bigtest#96]
The `@bigtest/mocha` readme instructs you to put side-effects in the hooks and assertions in the `it`s. This is causing slow tests to not be flagged in the test results, because the slowness is not in the test proper but rather a before hook. Total suite time appears to be counted properly. Here is a test one can run to demonstrate what I'm talking about:

```js
describe('slow side effects', function() {
  beforeEach(function() {
    return new Promise(resolve => {
      setTimeout(resolve, 200);
    });
  });

  it('reports the slow side effects', function() {
    expect(true).to.be.ok;
  });
});
```

When you run this test the results will not flag it as a slow test by appending the milliseconds to the test result:

![screen shot 2018-04-20 at 9 48 43 am](https://user-images.githubusercontent.com/671032/39054590-0d353494-4480-11e8-980e-076e4de41979.png)

I would like to see this:

![screen shot 2018-04-20 at 9 51 12 am](https://user-images.githubusercontent.com/671032/39054737-6496a8ee-4480-11e8-9868-2b340c52e714.png)

Yes, this seems more like a mocha API issue, but it is exacerbated by putting all side-effects in hooks as slow tests will almost never get flagged as far as I can tell. I am wondering if there are any changes we can make here to resolve this in some way.

**Comment by wwilsman** [comment]
Hey, thanks for the feedback!

This is actually possible if you don't use `@bigtest/mocha`. The speed comes from the convergent assertions, and you can create those in your normal mocha tests as well.

```javascript
import Convergence from '@bigtest/convergence';

describe('slow side effects', function() {
  it('reports the slow side effects', async function() {
    await new Promise(resolve => {
      setTimeout(resolve, 200);
    });

    // convergent assertion
    await new Convergence().when(() => {
      expect(true).to.be.ok;
    });
  });
});
```

This isn't very well documented, or ideal. So we'll be creating some helpers for doing these things without the need for `@bigtest/mocha`.

We're very close to releasing an updated docs site that will include guides that cover these things, so stay tuned! 😄

**Comment by robbiepitts** [comment]
Cool, thanks!
